# Use an official Python runtime as a parent image
FROM python:3.12-slim

# Copy the rest of the application's code
# Set our working directory
WORKDIR /app

# Copy the dependencies file to the working directory
COPY requirements.txt .
# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
# Add application code
COPY . .

# Make port 8080 available to the world outside this container
EXPOSE 8080

# Run the application
CMD ["python", "main.py"]