apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-assistant
  template:
    metadata:
      labels:
        app: ai-assistant
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000    
      containers:
        - name: ai-assistant
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
            privileged: false
            readOnlyRootFilesystem: true        
          image: ai-assistant # This will be replaced by Skaffold          
          ports:
            - containerPort: 8080
              name: http-server
          env:
            - name: VERSION
              value: "dev"
            - name: PORT
              value: "8080"
            - name: ENABLE_TRACING
              value: "false"
            - name: TOKEN_EXPIRY_SECONDS
              value: "3600"
            - name: PRIV_KEY_PATH
              value: "/tmp/.ssh/privatekey"
            # Valid levels are debug, info, warning, error, critical. If no valid level is set, gunicorn will default to info.
            - name: LOG_LEVEL
              value: "info"  
            # - name: PROJECT_ID
            #   value: "hackathon-bankofanthos-gke" # CHANGE_ME
            # - name: REGION
            #   value: "us-central1" # CHANGE_ME
            # - name: BALANCE_READER_SERVICE_ADDR
            #   value: "balancereader:8080"
            # - name: TRANSACTION_HISTORY_SERVICE_ADDR
            #   value: "transactionhistory:8080"
            # - name: ACCOUNTS_SERVICE_ADDR
            #   value: "accounts:8080"
          envFrom:
            - configMapRef:
                name: environment-config
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 10
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
              ephemeral-storage: 0.5Gi
            limits:
              memory: "256Mi"
              cpu: "500m"
              ephemeral-storage: 0.5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: ai-assistant
spec:
  type: ClusterIP
  selector:
    app: ai-assistant
  ports:
    - name: http
      port: 8080
      targetPort: 8080

